In [23]:
#numpay Assignment

#Q3
import math
import numpy as np
np.ones((4, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
#Q4
A = np.arange(10, 51,3)
print (A)
A[A % 2 == 0] = -1 
print (A)
        

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]
[-1 13 -1 19 -1 25 -1 31 -1 37 -1 43 -1 49]


In [33]:
# Q5 - a
A1 = np.arange(1,20,2)
print(A1)
A1[A1 % 3 == 0] = 0
print (A1)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  0  5  7  0 11 13  0 17 19]


In [49]:
#Q5-b
b=A1.reshape(2,5)
print(b)

[[ 1  0  5  7  0]
 [11 13  0 17 19]]


In [55]:
#Q5-c
b[:,2]=0
print(b)

[[ 1  0  0  7  0]
 [11 13  0 17 19]]


In [72]:
#Q6-a
b1=np.linspace(1.5,3,9)
print(b1)


[1.5    1.6875 1.875  2.0625 2.25   2.4375 2.625  2.8125 3.    ]


In [59]:
#Q6-b
np.random.seed(1234)
b2 = np.random.normal(1, 0.75, (3, 3))
b2
print(b2)

[[1.35357637 0.10676823 2.07453023]
 [0.76551108 0.45955845 1.66537221]
 [1.64469131 0.52260737 1.01177228]]


In [60]:
#Q6-c
c=np.linalg.det(b2)
print(c)

-1.0770051050177027


In [61]:
#Q6-d
b2.T

array([[1.35357637, 0.76551108, 1.64469131],
       [0.10676823, 0.45955845, 0.52260737],
       [2.07453023, 1.66537221, 1.01177228]])

In [63]:
#Q6-e convert b1 into 3*3 matrix
e=b1.reshape(3,3)
print(e)

[[1.5  1.67 1.84]
 [2.01 2.18 2.35]
 [2.52 2.69 2.86]]


In [87]:
#Q6-f  summation b1 and b2
f=b2.reshape(3,3)
print(e + f)

[[2.85357637 1.77676823 3.91453023]
 [2.77551108 2.63955845 4.01537221]
 [4.16469131 3.21260737 3.87177228]]


In [89]:
#Q6-g  multipliction b1 and b2
g=e*f
print(g)

[[2.03036456 0.17830294 3.81713562]
 [1.53867727 1.00183742 3.91362468]
 [4.1446221  1.40581383 2.89366872]]


In [80]:
#Q6-h
print(b2> b2.mean())

[[ True False  True]
 [False False  True]
 [ True False False]]


In [83]:
#Q6-i
print("min=" , b2.min())
print("max=" , b2.max())



min= 0.1067682289701517
max= 2.074530226319573
